"""create Phase 1 planning schema

Revision ID: 14f602f2e9a7
Revises:
Create Date: 2026-08-03 14:57:09.774443

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14f602f2e9a7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_token_hash"), "auth_sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "availability_windows",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "available", "unavailable", "preferred", name="availabilitytype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "energy_level",
            sa.Enum("high", "medium", "low", name="energylevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("day_of_week BETWEEN 0 AND 6", name="ck_availability_day"),
        sa.CheckConstraint("end_time > start_time", name="ck_availability_times"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_availability_windows_user_id"), "availability_windows", ["user_id"], unique=False
    )
    op.create_table(
        "semesters",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "active",
                "completed",
                "archived",
                name="semesterstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_semester_dates"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_semesters_user_id"), "semesters", ["user_id"], unique=False)
    op.create_index("ix_semesters_user_status", "semesters", ["user_id", "status"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("minimum_sleep_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_sleep_minutes", sa.Integer(), nullable=False),
        sa.Column("default_wake_time", sa.Time(), nullable=False),
        sa.Column("default_sleep_time", sa.Time(), nullable=False),
        sa.Column("maximum_daily_focus_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_session_minutes", sa.Integer(), nullable=False),
        sa.Column("minimum_break_minutes", sa.Integer(), nullable=False),
        sa.Column("freeze_window_minutes", sa.Integer(), nullable=False),
        sa.Column("preserve_free_time_percent", sa.Integer(), nullable=False),
        sa.Column("auto_apply_low_impact_changes", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("minimum_sleep_minutes > 0", name="ck_preferences_minimum_sleep"),
        sa.CheckConstraint(
            "preferred_sleep_minutes >= minimum_sleep_minutes",
            name="ck_preferences_preferred_sleep",
        ),
        sa.CheckConstraint(
            "preserve_free_time_percent BETWEEN 0 AND 100", name="ck_preferences_buffer"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "courses",
        sa.Column("semester_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("instructor", sa.String(length=120), nullable=True),
        sa.Column("credits", sa.Float(), nullable=True),
        sa.Column("current_grade", sa.Float(), nullable=True),
        sa.Column("target_grade", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("weekly_study_target_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 5", name="ck_course_difficulty"),
        sa.CheckConstraint("weekly_study_target_minutes >= 0", name="ck_course_study_target"),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semester_id", "code", name="uq_course_semester_code"),
    )
    op.create_index(op.f("ix_courses_semester_id"), "courses", ["semester_id"], unique=False)
    op.create_table(
        "fixed_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("semester_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recurrence_rule", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("commute_before_minutes", sa.Integer(), nullable=False),
        sa.Column("commute_after_minutes", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "commute_before_minutes >= 0 AND commute_after_minutes >= 0", name="ck_event_commute"
        ),
        sa.CheckConstraint("end_at > start_at", name="ck_event_times"),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_user_start", "fixed_events", ["user_id", "start_at"], unique=False)
    op.create_index(
        op.f("ix_fixed_events_semester_id"), "fixed_events", ["semester_id"], unique=False
    )
    op.create_index(op.f("ix_fixed_events_user_id"), "fixed_events", ["user_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("semester_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "paused", "completed", "archived", name="goalstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "critical", "high", "medium", "low", "optional", name="priority", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("target_description", sa.Text(), nullable=True),
        sa.Column("minimum_weekly_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_weekly_minutes", sa.Integer(), nullable=False),
        sa.Column("maximum_weekly_minutes", sa.Integer(), nullable=False),
        sa.Column("minimum_session_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_session_minutes", sa.Integer(), nullable=False),
        sa.Column("maximum_session_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_sessions_per_week", sa.Integer(), nullable=False),
        sa.Column("maintenance_weekly_minutes", sa.Integer(), nullable=False),
        sa.Column("reducible_during_busy_weeks", sa.Boolean(), nullable=False),
        sa.Column("progress_type", sa.String(length=64), nullable=True),
        sa.Column("current_progress", sa.Float(), nullable=True),
        sa.Column("target_progress", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "minimum_session_minutes <= preferred_session_minutes AND preferred_session_minutes <= maximum_session_minutes",
            name="ck_goal_session_effort",
        ),
        sa.CheckConstraint(
            "minimum_weekly_minutes <= preferred_weekly_minutes AND preferred_weekly_minutes <= maximum_weekly_minutes",
            name="ck_goal_weekly_effort",
        ),
        sa.CheckConstraint(
            "target_date IS NULL OR target_date >= start_date", name="ck_goal_dates"
        ),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_semester_id"), "goals", ["semester_id"], unique=False)
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "schedule_versions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("semester_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "accepted",
                "rejected",
                "superseded",
                name="schedulestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("objective_score", sa.Float(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("version_number > 0", name="ck_schedule_version_number"),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "version_number", name="uq_schedule_user_version"),
    )
    op.create_index(
        op.f("ix_schedule_versions_semester_id"), "schedule_versions", ["semester_id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_versions_user_id"), "schedule_versions", ["user_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("parent_task_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "skipped",
                name="taskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "critical", "high", "medium", "low", "optional", name="priority", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "flexibility",
            sa.Enum("fixed", "low", "medium", "high", name="flexibility", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "intensity",
            sa.Enum(
                "deep",
                "moderate",
                "light",
                "administrative",
                "passive",
                name="intensity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("remaining_minutes", sa.Integer(), nullable=False),
        sa.Column("minimum_session_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_session_minutes", sa.Integer(), nullable=False),
        sa.Column("maximum_session_minutes", sa.Integer(), nullable=False),
        sa.Column("earliest_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "deadline_at IS NULL OR earliest_start_at IS NULL OR deadline_at > earliest_start_at",
            name="ck_task_dates",
        ),
        sa.CheckConstraint("estimated_minutes > 0", name="ck_task_estimated_minutes"),
        sa.CheckConstraint(
            "minimum_session_minutes <= preferred_session_minutes AND preferred_session_minutes <= maximum_session_minutes",
            name="ck_task_session_effort",
        ),
        sa.CheckConstraint("remaining_minutes >= 0", name="ck_task_remaining_minutes"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_course_id"), "tasks", ["course_id"], unique=False)
    op.create_index(op.f("ix_tasks_goal_id"), "tasks", ["goal_id"], unique=False)
    op.create_index(op.f("ix_tasks_parent_task_id"), "tasks", ["parent_task_id"], unique=False)
    op.create_index("ix_tasks_user_deadline", "tasks", ["user_id", "deadline_at"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_table(
        "scheduled_blocks",
        sa.Column("schedule_version_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("fixed_event_id", sa.Uuid(), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("block_type", sa.String(length=32), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("stability_weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("end_at > start_at", name="ck_scheduled_block_times"),
        sa.CheckConstraint("stability_weight >= 0", name="ck_scheduled_block_stability"),
        sa.ForeignKeyConstraint(["fixed_event_id"], ["fixed_events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["schedule_version_id"], ["schedule_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_blocks_user_start", "scheduled_blocks", ["user_id", "start_at"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_blocks_fixed_event_id"),
        "scheduled_blocks",
        ["fixed_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_blocks_goal_id"), "scheduled_blocks", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_blocks_schedule_version_id"),
        "scheduled_blocks",
        ["schedule_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_blocks_task_id"), "scheduled_blocks", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_blocks_user_id"), "scheduled_blocks", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_blocks_user_id"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_task_id"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_schedule_version_id"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_goal_id"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_fixed_event_id"), table_name="scheduled_blocks")
    op.drop_index("ix_blocks_user_start", table_name="scheduled_blocks")
    op.drop_table("scheduled_blocks")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index("ix_tasks_user_deadline", table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_goal_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_course_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_schedule_versions_user_id"), table_name="schedule_versions")
    op.drop_index(op.f("ix_schedule_versions_semester_id"), table_name="schedule_versions")
    op.drop_table("schedule_versions")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_semester_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_fixed_events_user_id"), table_name="fixed_events")
    op.drop_index(op.f("ix_fixed_events_semester_id"), table_name="fixed_events")
    op.drop_index("ix_events_user_start", table_name="fixed_events")
    op.drop_table("fixed_events")
    op.drop_index(op.f("ix_courses_semester_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_table("user_preferences")
    op.drop_index("ix_semesters_user_status", table_name="semesters")
    op.drop_index(op.f("ix_semesters_user_id"), table_name="semesters")
    op.drop_table("semesters")
    op.drop_index(op.f("ix_availability_windows_user_id"), table_name="availability_windows")
    op.drop_table("availability_windows")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_hash"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
