"""track onboarding completion

Revision ID: fd59b35b7ee2
Revises: 14f602f2e9a7
Create Date: 2026-08-03 22:58:36.845274

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd59b35b7ee2"
down_revision: str | Sequence[str] | None = "14f602f2e9a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarding_completed_at")
    # ### end Alembic commands ###
