export const todayBlocks = [
  {
    time: "9:00",
    meridiem: "AM",
    title: "Algorithms lecture",
    detail: "ECS 125 · Fixed commitment",
    duration: "1h 20m",
    kind: "course",
    status: "up-next",
  },
  {
    time: "11:00",
    meridiem: "AM",
    title: "Problem set 3",
    detail: "CSC 320 · Deep work",
    duration: "50m",
    kind: "focus",
    status: "planned",
  },
  {
    time: "1:30",
    meridiem: "PM",
    title: "Research methods lab",
    detail: "PSYC 201 · Fixed commitment",
    duration: "1h 30m",
    kind: "course",
    status: "planned",
  },
  {
    time: "4:15",
    meridiem: "PM",
    title: "French practice",
    detail: "Personal goal · Light focus",
    duration: "30m",
    kind: "goal",
    status: "planned",
  },
];

export const courseCards = [
  {
    code: "CSC 320",
    name: "Algorithms and Data Structures",
    color: "violet",
    next: "Problem set 3",
    due: "Due in 3 days",
    progress: 68,
    target: "4h / week",
  },
  {
    code: "PSYC 201",
    name: "Research Methods",
    color: "blue",
    next: "Literature review",
    due: "Due Sep 18",
    progress: 42,
    target: "3h / week",
  },
  {
    code: "ECON 245",
    name: "Applied Microeconomics",
    color: "amber",
    next: "Chapter 4 reading",
    due: "Due Friday",
    progress: 80,
    target: "2.5h / week",
  },
  {
    code: "WRIT 109",
    name: "Academic Writing",
    color: "coral",
    next: "Essay outline",
    due: "Due Sep 22",
    progress: 25,
    target: "2h / week",
  },
];

export const goals = [
  {
    name: "Learn conversational French",
    category: "Language",
    cadence: "3 sessions per week",
    current: 90,
    target: 120,
    streak: "4 week rhythm",
    color: "mint",
  },
  {
    name: "Build interview confidence",
    category: "Career",
    cadence: "2 sessions per week",
    current: 50,
    target: 100,
    streak: "2 week rhythm",
    color: "violet",
  },
  {
    name: "Move three times a week",
    category: "Wellbeing",
    cadence: "3 sessions per week",
    current: 100,
    target: 135,
    streak: "6 week rhythm",
    color: "coral",
  },
];
